(defclass MOVINGAVERAGE (is-a USER)(role concrete)
     (slot Timestamp)
      (slot Indice)
      (slot Valor)
      (slot Papel)
      (slot Pregao)
      (slot Periodo)
      (slot ValidFrom)
      (slot ValidTo)
      (slot Origin)
      (slot Private)
)
